StatisticalTracker/Controllers/WagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.ClientServices.Providers;
using System.Web.Helpers;
using System.Web.Mvc;
using Excel;
using StatisticalTracker.Models;

namespace StatisticalTracker.Controllers
{
    [Authorize(Roles = "Over21, Admin")]
    public class WagerController : Controller
    {
        //
        // GET: /Wager/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Upload()
        {
            Session["Contests"] = string.Empty;
            return View();
        }

        public ActionResult ContestResults(string sort, string sortdir)
        {
            //Session["Contests"] = string.Empty;
            var contestMaster = new List<ContestModel>();
            contestMaster = (List<ContestModel>)Session["Contests"];

            if (!string.IsNullOrEmpty(sort))
            {
                switch (sort)
                {
                    case "EntryId":
                        if (sortdir == "ASC")
                        {
                            contestMaster = contestMaster.OrderBy(x => x.EntryId).ToList();
                        }
                        else if (sortdir == "DESC")
                        {
                            contestMaster = contestMaster.OrderByDescending(x => x.EntryId).ToList();
                        }
                        break;

                    case "ContestTitle":
                        if (sortdir == "ASC")
                        {
                            contestMaster = contestMaster.OrderBy(x => x.ContestTitle).ToList();
                        }
                        else if (sortdir == "DESC")
                        {
                            contestMaster = contestMaster.OrderByDescending(x => x.ContestTitle).ToList();
                        }
                        break;

                    case "Date":
                        if (sortdir == "ASC")
                        {
                            contestMaster = contestMaster.OrderBy(x => x.Date).ToList();
                        }
                        else if (sortdir == "DESC")
                        {
                            contestMaster = contestMaster.OrderByDescending(x => x.Date).ToList();
                        }
                        break;

                    case "Score":
                        if (sortdir == "ASC")
                        {
                            contestMaster = contestMaster.OrderBy(x => x.Score).ToList();
                        }
                        else if (sortdir == "DESC")
                        {
                            contestMaster = contestMaster.OrderByDescending(x => x.Score).ToList();
                        }
                        break;

                    case "Winnings":
                        if (sortdir == "ASC")
                        {
                            contestMaster = contestMaster.OrderBy(x => x.Winnings).ToList();
                        }
                        else if (sortdir == "DESC")
                        {
                            contestMaster = contestMaster.OrderByDescending(x => x.Winnings).ToList();
                        }
                        break;

                    case "EntryFee":
                        if (sortdir == "ASC")
                        {
                            contestMaster = contestMaster.OrderBy(x => x.EntryFee).ToList();
                        }
                        else if (sortdir == "DESC")
                        {
                            contestMaster = contestMaster.OrderByDescending(x => x.EntryFee).ToList();
                        }
                        break;
                }

            }

            return View(contestMaster);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ContestResults()
        {
            try
            {
                //Clears "Contests" session
                Session["Contests"] = string.Empty;
                
                var files = Request.Files;
                var contestMaster = new List<ContestModel>();

                for (int i = 0; i < files.Count; i++)
                {
                    if (files[i] == null) break;
                    if (files[i].ContentLength <= 0) continue;
                    string filePath = Path.Combine(HttpContext.Server.MapPath("../Uploads"),
                        Path.GetFileName(files[i].FileName));
                    
                    files[i].SaveAs(filePath);

                    var contests = ConvertExcelToDataSet(filePath);

                    // Foreach loop all contests in file to add to master collection
                    contestMaster.AddRange(contests);

                    // Sets session to "Contest" collection
                    Session["Contests"] = contestMaster;

                    ViewBag.Contests = contestMaster.Count();

                }

                

                return View("ContestResults", contestMaster);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Files are unable to be uploaded.  Please try again.";
                return View("Upload");
            }
        }
        
        private List<ContestModel> ConvertExcelToDataSet(string fileName)
        {
            DataSet data;
            var contestCollection = new List<ContestModel>();
            try
            {
                using (var stream = new FileStream(fileName, FileMode.Open))
                {
                    if (fileName.EndsWith(".xls") || fileName.EndsWith(".xslx"))
                    {
                        using (var excelReader = ExcelReaderFactory.CreateBinaryReader(stream))
                        {
                            excelReader.IsFirstRowAsColumnNames = true;
                            data = excelReader.AsDataSet();
                            contestCollection = ConvertDatasetToCollection(data);
                        }
                    }
                    else
                    {
                        using (var excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream))
                        {
                            excelReader.IsFirstRowAsColumnNames = true;
                            data = excelReader.AsDataSet();
                            contestCollection = ConvertDatasetToCollection(data);
                        }
                    }
                }
            }
            catch
            {
                ViewBag.ErrorMessage = "You have some invalid data in your dataset!";
                return new List<ContestModel>();
            }
            return contestCollection;
        }

        private static List<ContestModel> ConvertDatasetToCollection(DataSet data)
        {
            var contestCollection = new List<ContestModel>();

            for (var j = 0; j < data.Tables.Count; j++)
            {
                var numRows = data.Tables[j].Rows.Count;
                for (var i = 0; i < numRows; i++)
                {
                    // Reads and sets values of rows within selected table
                    if (data.Tables[j].Rows[i]["Score"].ToString() == string.Empty ||
                        data.Tables[j].Rows[i][13].ToString() == "voided" ||
                        data.Tables[j].Rows[i][13].ToString() == "endedunmatched") continue;
                    var entryId = data.Tables[j].Rows[i].Field<string>("Entry Id");
                    var sport = data.Tables[j].Rows[i].Field<string>("Sport");
                    var date = Convert.ToDateTime(data.Tables[j].Rows[i].Field<DateTime>("Date").Date);
                    var title = data.Tables[j].Rows[i].Field<string>("Title");
                    var salary = data.Tables[j].Rows[i].Field<string>("SalaryCap");
                    var score = data.Tables[j].Rows[i]["Score"] == null
                        ? 0.00
                        : data.Tables[j].Rows[i].Field<double>("Score");
                    var position = data.Tables[j].Rows[i]["Position"] == null
                        ? 0.00
                        : data.Tables[j].Rows[i].Field<double>("Position");
                    var entries = data.Tables[j].Rows[i]["Entries"] == null
                        ? 0.00
                        : data.Tables[j].Rows[i].Field<double>("Entries");
                    var opponent = data.Tables[j].Rows[i].Field<string>("Opponent");
                    var entryFee = Convert.ToDouble(data.Tables[j].Rows[i].Field<double>("Entry ($)"));
                    var winnings = Convert.ToDouble(data.Tables[j].Rows[i].Field<double>("Winnings ($)"));
                    var link = data.Tables[j].Rows[i].Field<string>("Link");

                    // Adds values of selected table to master collection
                    contestCollection.Add(new ContestModel()
                    {
                        EntryId = entryId,
                        Sport = sport,
                        Date = date,
                        ContestTitle = title,
                        SalaryCap = salary,
                        Score = score,
                        Opponent = opponent,
                        Position = position,
                        Entries = entries,
                        EntryFee = entryFee,
                        Winnings = winnings,
                        Link = link
                    });
                }
            }

            // Returns master collection
            return contestCollection;
        }
    }
}

StatisticalTracker/Views/Wager/ContestResults.cshtml
@using GridMvc
@using GridMvc.Html
@using GridMvc.Sorting
@using StatisticalTracker.Models
@using WebGridMvc
@model IEnumerable<ContestModel>
@{
    ViewBag.Title = "Contest Results";
}

<style type="text/css">
    .webGrid {
        margin: 4px;
        border-collapse: collapse;
        width: 500px;
        background-color: #B4CFC3;
    }

    .header {
        background-color: #C1D4E6;
        font-weight: bold;
        color: #FFF;
    }

    .webGrid th, .webGrid td {
        border: 1px solid #C0C0C0;
        padding: 5px;
    }

    .alt {
        background-color: #E4E9F5;
        color: #000;
    }

    .gridHead a:hover {
        text-decoration: underline;
    }

    .description {
        width: auto;
    }

    .select {
        background-color: #71857C;
    }
</style>
<h2>Contest Results</h2>
<br />
@Html.ActionLink("Return to Upload File Selection", "Upload")
<br />
<h2><b>Total Contests: @ViewBag.Contests</b></h2>
<br />
@{
        var grid = new WebGrid(Model, new[]
        {
            "EntryId",
            "ContestTitle",
            "Date",
            "SalaryCap",
            "Score",
            "Position",
            "Entries",
            "EntryFee",
            "Winnings",
            "Opponent"

        }, defaultSort:"Date", ajaxUpdateContainerId: "grid");
        //grid.Bind(Model);
}
<div id="grid">
    
    @grid.GetHtml(
    columns: grid.Columns(
        grid.Column("EntryId", "Entry Id", null, null, true),
        grid.Column("ContestTitle", "Contest Title", null, null, true),
        grid.Column("Date", "Date", null, null, true),
        grid.Column("SalaryCap", "Salary Cap", null, null, true),
        grid.Column("Score", "Score", null, null, true),
        grid.Column("Position", "Position", null, null, true),
        grid.Column("Entries", "Entries", null, null, true),
        grid.Column("EntryFee", "Entry Fee", null, null, true),
        grid.Column("Winnings", "Winnings", null, null, true),
        grid.Column("Opponent", "Opponent", null, null, true)
    ))
</div>

@*@Html.Grid(Model).Columns(columns =>
    {
        /* Adding not mapped column, that renders body, using inline Razor html helper
        @*columns.Add()
                .Encoded(false)
                .Sanitized(false)
                .SetWidth(30)
                .RenderValueAs(d =>
                    @<b>
                        @Html.ActionLink("Edit", "Index")
                    </b>);
    */
        // Adding "EntryID" column:
        columns.Add(o => o.EntryId)
                .Titled("EntryId")
                .SetWidth(100);

        // Adding "CompanyName" column:
        columns.Add(o => o.ContestTitle)
                .Titled("Contest Title")
                .SetWidth(200)
                //.ThenSortByDescending(o => o.OrderID)
                .SetFilterWidgetType("CustomCompanyNameFilterWidget");

        // Adding "Date" column:
        columns.Add(o => o.Date, "Date")
                .Titled("Date")
                .SortInitialDirection(GridSortDirection.Descending)
                .Format("{0:MM/dd/yyyy}")
                .SetWidth(110);

        // Adding "Salary Cap" column:
        columns.Add(o => o.SalaryCap)
            .Titled("Salary Cap")
            .SetWidth(50);
                //.RenderValueAs(o => CustomRenderingOfColumn(o));

        // Adding "Score" column:
        columns.Add(o => o.Score)
                .Titled("Score")
                .SetWidth(50);

        // Adding "Position" column:
        columns.Add(o => o.Position)
                .Titled("Position")
                .SetWidth(50);

        // Adding "Entries" column:
        columns.Add(o => o.Entries)
                .Titled("Entries")
                .SetWidth(50);

        // Adding "Opponent" column:
        columns.Add(o => o.Opponent)
                .Titled("Opponent")
                .SetWidth(150);


    })).WithPaging(15)
    .Sortable()
    .Filterable()
    .WithMultipleFilters()*@

@*@if (Model != null)
    {

        <table style="border: black">
            <thead>
                <tr>
                    <td>EntryId</td>
                    <td>Sport</td>
                    <td>Date</td>
                    <td>ContestTitle</td>
                    <td>SalaryCap</td>
                    <td>Score</td>
                    <td>Position</td>
                    <td>Entries</td>
                    <td>Opponent</td>
                    <td>EntryFee</td>
                    <td>Winnings</td>
                    <td>Link</td>
                </tr>
            </thead>
            <tbody>

                @foreach (var m in Model)
                {
                    <tr>
                        <td>@m.EntryId</td>
                        <td>@m.Sport.ToUpper()</td>
                        <td>@m.Date.Date.ToShortDateString()</td>
                        <td>@m.ContestTitle</td>
                        <td>@m.SalaryCap</td>
                        <td>@m.Score</td>
                        <td>@m.Position</td>
                        <td>@m.Entries</td>
                        <td>@m.Opponent</td>
                        <td>@string.Format("{0}",m.EntryFee)</td>
                        <td>@string.Format("{0}",m.Winnings)</td>
                        <td>@m.Link</td>

                    </tr>
                }


            </tbody>
        </table>
    }*@

StatisticalTracker/Views/Wager/Index.cshtml
@{
    ViewBag.Title = "1-800-GAMBLER";
}

<h2>1-800-GAMBLER</h2>

<h3>@Html.ActionLink("Upload DFL File", "Upload","Wager")</h3>

StatisticalTracker/Views/Wager/Upload.cshtml
@model IEnumerable<StatisticalTracker.Models.ContestModel>
@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>

<div>
    @using (Html.BeginForm("ContestResults", "Wager", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input name="uploadFiles[]" id="uploadFile" type="file" multiple />
        <br />
        <input type="submit" id="upload" value="Upload File(s)" title="Upload file" onclick=" return checkfilename(); " />
    }
</div>

StatisticalTracker/Views/Wager/_ContestPartial.cshtml
@model IEnumerable<StatisticalTracker.Models.ContestModel>
@{
    ViewBag.Title = "Contests";
}

<table>
    <tbody>
        
            @foreach (var m in Model)
            {
                <tr>
                    <td>@m.EntryId</td>
                    <td>@m.Sport</td>
                    <td>@m.Date</td>
                    <td>@m.ContestTitle</td>
                    <td>@m.SalaryCap</td>
                    <td>@m.Score</td>
                    <td>@m.Position</td>
                    <td>@m.Entries</td>
                    <td>@m.Opponent</td>
                    <td>@m.EntryFee</td>
                    <td>@m.Winnings</td>
                    <td>@m.Link</td>

                </tr>
            }
        

    </tbody>
</table>